#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/ci/test-and-build-nixie"

cd "${DIR}/../.."

# Buildx Builder
docker buildx create --name "Buildx-NPM" || echo
docker buildx use "Buildx-NPM"

if [ "${BUILD_TAG:-0}" != 0 ]; then
	docker buildx build -f docker/Dockerfile-nixie $BUILD_TAG --platform $BUILD_PLATFORM . --push
else
	docker buildx build -f docker/Dockerfile-nixie -t "nixielectra/nginx-proxy-manager:dev" --platform $BUILD_PLATFORM . --push
fi

docker buildx rm "Buildx-NPM"

echo "Multiarch build Complete"